# https://grafana.com/docs/loki/latest/send-data/promtail/configuration/#positions
positions:
  filename: /logs/positions.yaml

clients:
  - url: http://loki-local:3100/loki/api/v1/push

# https://grafana.com/docs/loki/latest/send-data/promtail/configuration/#scrape_configs
scrape_configs:
  - job_name: telegram-bot
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /logs/bot.log
  - job_name: user-manager
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /logs/manager.log
